language: python

python:
  - "3.7"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get update -y
  - sudo apt-get install -y python-pytest
  - sudo apt-get install cpputest
  - sudo pip install codecov
  - sudo apt install python3-pip
  - pip install setuptools

install:
  - sudo apt install software-properties-common
  - sudo apt install gcc-7 g++-7 gcc-8 g++-8 gcc-9 g++-9
  - pip install coverage
  - pip install pytest-cov==2.11.1 
  - pip install python-dev-tools

script:
  
  #- (cd src && CC=gcc-4.8 CXX=g++-4.8 make -f Makefile-custom test)
  - cd RobocupWrapper 
  - pip3 install -e.
  - CC=g++-7 python setup01.py install
  - ls
  - which python
  - cpp -v /dev/null -o /dev/null
  - g++ test.cc -o test -I/travis/virualenv/python3.7.1/include/python3.7 -lpython3.7 

  - ./test
  - #python -m pytest test.py # run tests
  - #py.test test.py --cov=.
