language: python
python:
  - 3.6
before_install:
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt 
  - pip install coverage
  - pip install pytest-cov==2.11.1 

script: 
  - cd RobocupWrapper 
  - pwd
  - pip install .
  - python3 setup01.py build_ext --inplace
  - python -m pytest test.py # run tests
  - py.test test.py --cov=.


after_success:
  #- codecov 
  - bash <(curl -s https://codecov.io/bash)
