language: python
python:
  - 3.6
before_install:
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt 
script: 
  - pwd
  - cd ExampleWrap 
  - pip3 install .
  - python setup.py build
  - python -m pytest test.py # run tests
after_success:
 # - codecov # submit coverage
  - bash <(curl -s https://codecov.io/bash)
