language: python
python:
  - 2.7
  - 3.6
before_install:
  - pip install -U pytest-3
  - pip install codecov
install:
  - pip install -r requirements.txt 
script: 
  - python -m pytest-3 ExampleWrap.test # run tests
after_success:
  - codecov # submit coverage