language: python
python:
  - 3.6
before_install:
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt 
  - pip install coverage
  - pip install pytest-cov==2.11.1 

script: 
  - cd ExampleWrap 
  - pip3 install .
  - python setup.py build
  - python -m pytest test.py # run tests
  - coverage run -m pytest 
  - py.test test.py --cov=myModule.cpp

after_success:
  #- codecov 
  - bash <(curl -s https://codecov.io/bash)
