os: linux
dist: focal
language: python
python:
  - 3.8

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get update -y
  - sudo apt-get install -y python-pytest
  - sudo apt-get install cpputest
  - sudo pip install codecov
  - sudo apt install python3-pip
  - pip install setuptools

install:
  - sudo apt install software-properties-common
  #- sudo apt install gcc-7 g++-7 gcc-8 g++-8 gcc-9 g++-9
  - pip install coverage
  - pip install pytest-cov==2.11.1 
  - pip install pytest-cov pytest
  - pip install codecov
  - pip install python-dev-tools
  - cd RobocupWrapper 
  - pip3 install -e.
  
script:
  - cd Code_Base
  - cd behaviors
  - coverage run -m pytest test.py
  - coverage report -m
  
  after_success:
    - codecov
