language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U unittest
  - pip install codecov
install:
  - pip install -r requirements.txt 
script: 
  - python -m unittest ExampleWrap.test # run tests
after_success:
  - codecov # submit coverage