language: python
python:
  - 2.7
  - 3.5
  - 3.6
before_install:
  #- python --version
  #- pip install -U pip
  #- pip install -U unittest
  - pip install codecov
install:
  #- pip install ".[test]" . # install package + test dependencies
  #
script: 
  - python -m unittest ExampleWrap.test # run tests
after_success:
  - codecov # submit coverage