language: python

python:
  - "3.7"

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get update -y
  - sudo apt-get install -y python-pytest
  - sudo pip install codecov
  - sudo apt install python3-pip

install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  #- CC=g++-4.8 python setup.py install
  #- sudo apt-get -r requirements.txt 
  - sudo apt-get coverage
  - sudo apt-get pytest-cov==2.11.1 

script:
  #- python setup.py test
  #- (cd src && CC=gcc-4.8 CXX=g++-4.8 make -f Makefile-custom test)
  - cd RobocupWrapper 
  - pip3 install -e.
  - CC=g++-4.8 python3 setup001.py build_ext --inplace
  - python -m pytest test.py # run tests
  - py.test test.py --cov=.

###############################################################3

#   before_install:
#     - pip install -U pytest ##done
#     - pip install codecov
#   install:
#     - pip install -r requirements.txt 
#     - pip install coverage
#     - pip install pytest-cov==2.11.1 

#   script: 
  
#     - cd RobocupWrapper 
#     - pip3 install -e.
#     - python3 setup001.py build_ext --inplace
#     - python -m pytest test.py # run tests
#     - py.test test.py --cov=.


#   after_success:
#     #- codecov 
#     - bash <(curl -s https://codecov.io/bash)

