language: python
python:
  - 2.7
  - 3.6
before_install:
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt 
script: 
  - python -m pytest ExampleWrap/test.py # run tests
after_success:
  - codecov # submit coverage